### ISSUE TITLE
test failing on stable and oldstable 

### ISSUE THREAD

**Issue by hmconorthwestu** [bywatersolutions/dev-koha-plugin-kitchen-sink#16]
All pushes on forked repositories are passing tests on master, but on stable and old stable the docker container isn't running after the three-minute sleep. Here's the error I'm getting, even on a repository that previously passed tests (and I only changed an indent to be able to commit):

WAKING UP
Error response from daemon: Container 992c3cfda6ca49eb4a3fc251ccd0ee1a4f53bffde9120cfecb9cc5998faa499c is not running
Error: Process completed with exit code 1.

Example repository I'm seeing this on: https://github.com/hmconorthwestu/koha-plugin-shelfreading

**Comment by kylemhall** [comment]
It looks like you got this figured out!
