### ISSUE TITLE
cron error message: Argument "{VERSION}" isn't numeric after installation in Koha 21.11

### ISSUE THREAD

**Issue by udgithub** [bywatersolutions/dev-koha-plugin-kitchen-sink#18]
Hello Bywatersolutions !

we are new to Koha and tried to use your demo plugin.
It works well but we get a cron error message.

**cron mail subject**
    Cron <user@server> koha-foreach --chdir --enabled --email /usr/share/koha/bin/cronjobs/process_message_queue.pl

**cron error message**
`
Argument "{VERSION}" isn't numeric in int at /usr/share/koha/lib/Koha/Plugins/Base.pm line 329.
Argument "{VERSION}" isn't numeric in int at /usr/share/koha/lib/Koha/Plugins/Base.pm line 329.
Plugin hook before_send_message called with the params: $VAR1 = {
          'type' => '',
          'verbose' => 0,
          'letter_code' => undef,
          'limit' => undef
        };`

In line 329 of Base.pm you find the sub _version_compare !

What can we do to change this?

Thanks a lot in advance for your help.
And thanks a lot for all your cool videos and other helpful information concerning Koha.

Best regards

**Comment by kylemhall** [comment]
Thanks for letting me know! This is now fixed in the latest release, v2.2.2! If you install this new version that warning should go away.
